### ISSUE TITLE
Task List

### ISSUE THREAD

**Issue by swoolcock** [swoolcock/rush#1]
- [ ] Installation instructions
- [ ] Better player sprite
- [ ] Rewinding
- [ ] Boss sprite during kiai sections
- [ ] Saw blades
- [ ] Hammers and other minion variants
- [ ] Health bar
- [ ] Health pickups
- [ ] Custom avatars/abilities via mods
